### ISSUE TITLE
The version on the vcpkg is out of date

### ISSUE THREAD

**Issue by VirFunc** [google/marl#125]
Hello, I got ```marl``` from **vcpkg**. It seems that the version on vcpkg has not been updated for a long time. When I wanted to include ```event.h```, I found that there was no such file.

**Comment by ben-clayton** [comment]
Hi @VirFunc,

@myd7349 kindly added the vcpkg definition.

I'm not overly familiar with vcpkg. I'm guessing that [the `version:` field of this file needs to be updated](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/ports/marl/CONTROL#L2)?

Having never actually used this package manager, I'm probably not the best person to be making blind changes to these files. I have no issues with someone else updating the revision though.

Cheers,
Ben

**Comment by strega-nil** [comment]
This should be solved by microsoft/vcpkg#11465, which just got merged :)

**Comment by ben-clayton** [comment]
Thank you very much @myd7349 and @strega-nil !
