### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by tangobravo** [google/marl#126]
Marl looks really interesting but my codebase primarily targets mobile, so I'd need support for both iOS and Android. Is iOS support on the cards at all?

A bit of background - my codebase does real-time CPU-side camera processing and many of the high CPU parts could be split across cores relatively easily. The work is non-blocking so I don't think I really need fibers or yielding, I just want to spread it out between workers.

I was thinking of writing a simple dispatch queue type of thing where workers would just all pull the next job from a shared queue, but thought I'd look at some of the more complete third-party library solutions. If you think marl is overkill for this use case then that would be really helpful to hear too!

There might even be standard library solutions that will work - I've been slow to learn what's new in C++ as historically the codebase worked with lots of old / esoteric compilers (old MSVC, Symbian, Android ndk before it had a standard library...). I have started adopting some new features from C++11 but I haven't dedicated much time to learning all the new stuff.

**Comment by ben-clayton** [comment]
Hi @tangobravo,

While I'm not aware of anyone using marl on iOS, I think there's a good chance it would work without changes. The most likely part to have trouble would be the fiber switching assembly for arm64, but this is fairly well tested battle tested for Android, and unless there's iOS specific differences I'm unaware of, I think this should Just Work.

If you don't use any of the blocking calls, there will be no fiber switches, and you'll simply be using marl's work stealing task scheduler. There are other projects out there that provide multithreaded job schedulers, but I'm not familiar enough with them to advise. 

If you do try using marl, I'd be very interested in hearing how well it works on iOS. 

Cheers,
Ben

**Comment by tangobravo** [comment]
Thanks for the quick reply @ben-clayton!

Would calling conventions have any impact on the assembly required for fiber switching? iOS has a few differences in this respect, documented here:
https://developer.apple.com/library/archive/documentation/Xcode/Conceptual/iPhoneOSABIReference/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009020-SW1

I'll let you know if I do give it a go - CMake's iOS support is still not great AFAIK (there's a third-party toolchain file that most seem to use), in the past I've just added source files into an Xcode project manually and adjusted include paths etc.

Having "official" iOS support would probably help adoption in the mobile space - I suspect many people considering a C++ solution for android would be likely to want an iOS build of their codebase too.

**Comment by benvanik** [comment]
We too are interested in iOS support!

**Comment by ben-clayton** [comment]
Sorry for the slow reply - I've been on staycation.

> Would calling conventions have any impact on the assembly required for fiber switching? 

Yes, quite possibly. Sounds like I should try and obtain an iOS device and give this a try.

> I'll let you know if I do give it a go - CMake's iOS support is still not great AFAIK (there's a third-party toolchain file that most seem to use), in the past I've just added source files into an Xcode project manually and adjusted include paths etc.

Makes sense. I'm not overly opposed to adding XCode build files so long as they can be sensibly maintained.

> Having "official" iOS support would probably help adoption in the mobile space - I suspect many people considering a C++ solution for android would be likely to want an iOS build of their codebase too

Anything "official" needs maintenance, and at the very least CI testing. I'm not sure that our current CI solution offers anything that can do real on-device testing. We do have mac bots though, so perhaps the iOS emulator will be sufficient. I'll investigate.

> We too are interested in iOS support!

Ack. As you're a googler who is dealing with iOS, perhaps you have some solutions in place for iOS testing? Let's chat!

Thanks,
Ben

**Comment by tangobravo** [comment]
> Anything "official" needs maintenance, and at the very least CI testing. I'm not sure that our current CI solution offers anything that can do real on-device testing. We do have mac bots though, so perhaps the iOS emulator will be sufficient. I'll investigate.

I don't underestimate the amount of work involved in making it "official" so thanks for considering it 👍 

Unfortunately the iOS simulator isn't an emulator - it's implemented as a separate x86_64 platform.

**Comment by ben-clayton** [comment]
> Unfortunately the iOS simulator isn't an emulator - it's implemented as a separate x86_64 platform.

Shame.

Okay, let me investigate whether I can obtain an iOS device from somewhere. I'll get back to you when I have an update.

Cheers,
Ben

**Comment by ben-clayton** [comment]
I've ordered a iPhone SE which should arrive this weekend. I should be able to look into this next week.

**Comment by ben-clayton** [comment]
So, after _finally_ figuring out how to actually build and deploy using XCode, I can confirm that all the unit tests pass on a iPhone SE. There were a few compiler warnings raised, which I'll put a PR up to fix. 

I'll next look through @tangobravo's linked document to double check any documented ABI differences that might cause problems that aren't covered by the existing tests.

**Comment by ben-clayton** [comment]
So I've scanned the ABI doc - as far as I can tell, there's nothing in there that should cause issues with marl.

I think we can say marl is supported on iOS.

**Comment by tangobravo** [comment]
Awesome 🎉 - thanks for the work and the update!

I assume your tests have been limited to arm64? iOS 11 and later is 64-bit only and all devices since iPhone 5S have been 64-bit, so it's not a deal-breaker, but on the tablet side older devices are a bit more common. Testing-wise there are various remote test services that should allow running 32 bit apps as long as they're on iOS 10 or below.

I've also got an iPad Mini 2 here that maxed out at iOS 9 - I'm happy to give the test suite a run on there if you've got a Xcode project for it now.

**Comment by ben-clayton** [comment]
> I assume your tests have been limited to arm64? 

Correct. I didn't even consider arm32 is a thing for iOS any more.

> I've also got an iPad Mini 2 here that maxed out at iOS 9 - I'm happy to give the test suite a run on there if you've got a Xcode project for it now.

That would be great, thank you!

I appear to have created a project, but I have no idea what is user config and what is essential. I'm an absolute iOS / XCode novice.
It's probably easier to tell you how I created it, than attempting to figure out how to bundle it and send it to you:
* `File` -> `New` -> `Project...`
* Create a `Single View App`
* Add all the `marl/src/*` source files to the project, except for `*_bench.*`.
* Add the `marl/third_party/googletest/googletest/src/gtest-all.cc` source file to the project.
* Add to the `Header Search Paths`:
  * `marl/include`
  * `marl/third_party/googletest/googlemock/include`
  * `marl/third_party/googletest/googletest/include`
  * `marl/third_party/googletest/googletest`
* Delete the `main` from the `Single View App` template - it's already defined by `marl/src/marl_test.cpp` (just try building to find it - you'll get a duplicate symbol error)

This should build and run.

Please shout if this doesn't work.

Thanks again,
Ben
