### ISSUE TITLE
Make worker thread stack size adjustable per Scheduler

### ISSUE THREAD

**Issue by benvanik** [google/marl#128]
As mentioned in issue #12 and the TODO here:
https://github.com/google/marl/blob/0591f0ef0811eff9e87c22048abc048c0399862d/include/marl/scheduler.h#L245-L246

(filing so that it's easier for contributors to pick up the TODO :)

**Comment by ben-clayton** [comment]
Thanks Ben.

Yes, this should really be addressed.
It's partly blocked by #12, which likely needs some hand rolled assembly for Win32 / Win64 fiber switching.

Very happy to accept a PR if anyone is feeling brave enough to implement this!

**Comment by a952135763** [comment]
#12 has been solved.
The FiberStackSize can be configured.
Win32 / Win64  stackSize is rounded up to the system's allocation granularity (typically 64 KB).
