### ISSUE TITLE
Question: is the bind/unbind and implicit single threaded worker optional?

### ISSUE THREAD

**Issue by benvanik** [google/marl#130]
How load-bearing is bind/unbind? Looking at the marl::schedule implementation it seems like if I have a Scheduler* I should be able to enqueue work, and if I was always enqueuing work for asynchronous execution (that I *never* want to block the enqueuing thread) the logic in bind/unbind seems unneeded.

Is it safe to just use `scheduler->enqueue()` if I always have a >0 worker count and don't need the single threaded work queue adoption behavior?

(we are ourselves a framework that can make no assumptions about the calling thread that enqueues work as it may be anything from the UI thread in an Android app calling through JNI to an external executor calling in expecting non-blocking behavior just as marl itself does, etc)

**Comment by ben-clayton** [comment]
Hi Ben,

Yes, you can schedule tasks without calling `bind()` and `unbind()` **so long as the scheduler has dedicated worker threads** by calling `marl::Scheduler::enqueue()`. Attempting to call this on a scheduler with no dedicated workers will error and abort.
I've created #134 to verify this behaviour.

> I should be able to enqueue work, and if I was always enqueuing work for asynchronous execution (that I never want to block the enqueuing thread) the logic in bind/unbind seems unneeded.

Out of curiosity, how do you intend to synchronize on the work submitted?

**Comment by benvanik** [comment]
Good question :)

As I'm (effectively) emulating the Vulkan scheduling model where I have multiple queues processing work and timeline semaphores for signaling between/within each queue my thought was to use tickets within the scheduler and have a task for each semaphore signal that'll update the value of my timeline semaphore. External code will then be waiting on the semaphore (which internally is a non-marl condvar) or querying the current value to see if the timepoint has been reached.

The question about bind/unbind here fits in this model where the (equivalent) vkQueueSubmit may be coming from any thread and I want that not to block; so my vkQueueSubmit would be doing scheduler->enqueue and then I'd be using timeline semaphores for the actual bidirectional signaling.

The thing I'll need to play with is how a "device-side" semaphore wait will use marl-compatible wait behavior while a "host-side" semaphore wait will use normal host behavior. It looks like WaitGroup::wait may do this for me (marl's condvar will switch based on whether its within a fiber thread or not), so I may be able to just use that.

An enhancement that would make this cleaner would be adding a marl-native Fence that instead of waiting for a particular done() count like WaitGroup would wait for some payload to be >= a value before resuming. This reduces the amount of tracking that'd be required otherwise, and should have about the same complexity as WaitGroup does (being built on marl's condvar). That's one of the things I love about how marl is layered - hopefully just a few dozen lines of code without a lot of tricky stuff :)

**Comment by ben-clayton** [comment]
Makes sense.

> An enhancement that would make this cleaner would be adding a marl-native Fence that instead of waiting for a particular done() count like WaitGroup would wait for some payload to be >= a value before resuming. This reduces the amount of tracking that'd be required otherwise, and should have about the same complexity as WaitGroup does (being built on marl's condvar). 

Yes, it should be trivial to build something like this with `marl::ConditionVariable`.

Have I answered your original question? Safe to close this issue?
