### ISSUE TITLE
No longer using fiber API on Windows

### ISSUE THREAD

**Issue by a952135763** [google/marl#176]
I think fiber api and ucontext api can no longer be used.
You can use the core code of boost.context to obtain higher performance and smaller stack space.
The smaller stack space on the X32 platform means more tasks can be opened.
What do you think?

**Comment by ben-clayton** [comment]
Hi @a952135763,

> I think fiber api and ucontext api can no longer be used.

I haven't touched / used the ucontext code in a long time, might entirely be broken, and probably should just be removed.
However, I'm not sure what you mean by _"I think fiber api ... can no longer be used."_ Please can you elaborate?

> You can use the core code of boost.context to obtain higher performance and smaller stack space.

Marl has zero dependencies, and I'd like to keep it that way. Again, please can you elaborate on how boost provides _"higher performance and smaller stack space"_? As of https://github.com/google/marl/pull/173, the stack size is configurable, and I'm not aware that marl's fiber assembly routines are slower than alternatives? Do you have benchmarks to show otherwise?

Many thanks,
Ben

**Comment by a952135763** [comment]
#173  the stack size is configurable!
However, the minimum stack size of Windows platform is 64KB(Follow system settings). Setting it to smaller will not take effect.
I implemented the boost.context A simple benchmark will be provided later

**Comment by ben-clayton** [comment]
> I think fiber api and ucontext api can no longer be used.

So if I understand you correctly, you saying that the Win32 Fiber API does not give you the small enough stacks for your needs, and ucontext does not work as an alternative as its unavailable on Windows. Is that correct?

> I implemented the boost.context 

I took a look at your branch, and it looks like you've copied the assembly files out of the boost library. Unfortunately we cannot accept this code, unless the original author contributes this with the file licenses changed to marl's.

> A simple benchmark will be provided later

This would be interesting to see all the same. If the assembly version significantly out performs the Win32 API, then this is more compelling reason for someone to implement win32 / win64 assembly fibers for marl.

Note, marl already has a large collection of benchmarks which can be built with the `-DMARL_BUILD_BENCHMARKS` CMake flag. [`tools/cmd/benchdiff/main.go`](https://github.com/google/marl/blob/main/tools/cmd/benchdiff/main.go) can also be used to diff two benchmark files.

Cheers,
Ben

**Comment by a952135763** [comment]
>I took a look at your branch, and it looks like you've copied the assembly files out of the boost library. Unfortunately we cannot accept this code, unless the original author contributes this with the file licenses changed to marl's.
Well, I will continue to explore other solutions.
In fact, I also rewrote the fiber api under the windows platform.Not perfect yet

**Comment by ben-clayton** [comment]
I don't think there's anything particularly actionable for me in this issue. We've discussed the desire for a Windows fiber assembly implementation so that stack sizes can be smaller than 64KB, but that should probably be filed as a new feature request.
Closing for now.
