### ISSUE TITLE
[Question] implemention of function alignedFree()

### ISSUE THREAD

**Issue by snowzhaozhj** [google/marl#220]
https://github.com/google/marl/blob/166fc600772eb530749293446153e444eac4a993/src/memory.cpp#L195
I wonder why `sizeof(size_t)` is used here instead of `sizeof(void*)`, even though the values of the two are equal on my computer.

**Comment by ben-clayton** [comment]
Hi @snowzhaozhj,
While these are usually the same size, I agree, this just looks wrong. Thanks for spotting. I'll put a fix up shortly.
