### ISSUE TITLE
[Question] Scheduler suspend/resume and stop

### ISSUE THREAD

**Issue by zhucy-maker** [google/marl#224]
Hi,
I have the following two questions to consult：
1）Does marl support stop the Scheduler in time  when some tasks is running?
2）Does marl support suspend/resume the Scheduler?

**Comment by ben-clayton** [comment]
Hello,

1. No. Submitted task need to execute and return before the scheduler is destructed. While unstarted tasks, could in theory be discarded, this is not currently supported. It would be risky to abort tasks that have been started and are suspended as they will likely have objects on the stack, and state that needs tearing down.
2.  Currently no first-class support for this, but you could schedule some tasks that block until some event is triggered. It shouldn't be too hard to add first-class support for this, but the `Scheduler::suspend()` call would likely have to block until all worker threads become idle. This will take as long as the submitted tasks take to complete / yield.

Cheers,
Ben

**Comment by zhucy-maker** [comment]
Thank you for your reply.
