### ISSUE TITLE
what's the difference between task and fiber?

### ISSUE THREAD

**Issue by 315567599** [google/marl#233]
rt

**Comment by ben-clayton** [comment]
Hello,

Does https://github.com/google/marl/blob/main/docs/scheduler.md help answer your question?

Cheers,
Ben

**Comment by 315567599** [comment]
Hello Ben,

A task is created by marl::schedule(). My question is how to create a fiber?

Thanks & Best Regards

**Comment by 315567599** [comment]
when a task is blocked, how the task become a fiber?  I can't understand the detail.

**Comment by 315567599** [comment]
Thanks very much for help。but i  still don't understand when a fiber was created. and why at that time?

**Comment by 315567599** [comment]
By reading code, Scheduler:: Worker:: suspend may be the key to understanding. Can you explain this function in an easy way?

**Comment by ben-clayton** [comment]
If the fiber running on a thread becomes blocked, and there's additional tasks to run, you want to have the thread be able to suspend the execution of the currently executing & blocked task, and have the thread run another task.
To do this without requiring a callback or promise pattern (the main purpose of marl), we require another fiber of execution. Fibers are pooled. If the pool has no free fibers available, then we construct a new one to start executing the next task.

**Comment by 315567599** [comment]
> If the fiber running on a thread becomes blocked, and there's additional tasks to run, you want to have the thread be able to suspend the execution of the currently executing & blocked task, and have the thread run another task.
To do this without requiring a callback or promise pattern (the main purpose of marl), we require another fiber of execution. Fibers are pooled. If the pool has no free fibers available, then "we construct a new one to start executing the next task".

we construct a new one to start executing the next task
which function does above job?

**Comment by ben-clayton** [comment]
> which function does above job?

It's constructed here:
https://github.com/google/marl/blob/a47a3a5c54435751d30e3154fdf17e3b29fc6796/src/scheduler.cpp#L496

**Comment by 315567599** [comment]
very thanks, your kindly answer help me a lot.  I try to continue read and debug the code.

**Comment by ben-clayton** [comment]
No worries. Closing for now.

Please don't hesitate to file more issues if you have further questions.
