### ISSUE TITLE
crashed when Scheduler::Worker::tryLock

### ISSUE THREAD

**Issue by 315567599** [google/marl#256]
![image](https://github.com/google/marl/assets/8306636/c024914b-1ef3-4eb7-8929-b1b0d93aa5be)

**Comment by ben-clayton** [comment]
Sorry, but I'm going to need a bit more information to help diagnose the issue here.

Based on the limited information I have, I would guess that you've destructed the `Scheduler` and then attempted to schedule new work.

**Comment by 315567599** [comment]
yes, it work now. Thanks ben:)
