### ISSUE TITLE
Does marl support switching context while unwinding stack? i.e. is it exception safe?

### ISSUE THREAD

**Issue by feverzsj** [google/marl#263]
I know windows fiber is exception safe with proper compiler flags. But gcc/llvm based implementations typically require save/restore cxa global states while switching context to assure correct exception behaviour, which I didn't find in the source.

**Comment by ben-clayton** [comment]
Probably not. I'm not aware of marl being used in any project with exceptions enabled, and I certainly didn't consider exceptions during implementation. Sorry.
