### ISSUE TITLE
implicit capture of `this` causes build failures

### ISSUE THREAD

**Issue by dneto0** [google/marl#271]
With Clang 10:
```
/[tmpfs/src/github/marl/src/scheduler.cpp:370](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/github/marl/src/scheduler.cpp?l=370):48: error: explicit capture of 'this' with a capture default of '=' is a C++20 extension [-Werror,-Wc++20-extensions]
      thread = Thread(std::move(affinity), [=, this] {
```
With GCC 9:
```
[ 32%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
/tmpfs/src/github/marl/src/scheduler.cpp: In member function 'void marl::Scheduler::Worker::start()':
/[tmpfs/src/github/marl/src/scheduler.cpp:370](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/github/marl/src/scheduler.cpp?l=370):48: error: explicit by-copy capture of 'this' redundant with by-copy capture default [-Werror]
  370 |       thread = Thread(std::move(affinity), [=, this] {
      |                                                ^~~~
```
Caused by #266

**Comment by amaiorano** [comment]
One workaround would be to use ref-capture along with explicit copy-capture for the values we use in the lambda by copy. For example: https://godbolt.org/z/6KcTrqjeP - set `EXPLICIT_THIS_CAPTURE` to 0 and note that it compiles without warnings. Ref-capture will capture 'this' always. We just have to be careful to explicitly capture the referenced variables by value.

**Comment by dneto0** [comment]
Right, but I'm not that familiar with this code and it's more fragile to do the explicit captures of everything else.
It's only two spots in the code, so I'm not too worried about using the macro.
