### ISSUE TITLE
Single-threaded workers should probably not steal work

### ISSUE THREAD

**Issue by ben-clayton** [google/marl#29]
As raised in #17, it is somewhat unexpected to see non-dedicated-worker threads executing tasks when there are dedicated workers available.

After consideration, I think that this behavior is probably a Bad Idea™.
Tasks that are stolen by the single threaded worker may yield, and sit on the single threaded worker queue, indefinitely, potentially leading to a potential deadlock.

A simple solution here is to prevent work stealing for the single-threaded workers.

**Comment by facontidavide** [comment]
What should I say... I agree ;)
