### ISSUE TITLE
Warning treated as error in 32 bit Windows builds with MSVC in ANGLE

### ISSUE THREAD

**Issue by sugoi1** [google/marl#38]
In ANGLE, trying to build a 32 bit Windows version including SwiftShader.

gn args:
is_debug=true
is_clang=false
target_cpu="x86"

Warning message:
...\angle\third_party\SwiftShader\third_party\marl\include\marl/pool.h(241): note: see reference to function template instantiation 'std::shared_ptr<marl::BoundedPool<sw::DrawCall::BatchData,16,marl::PoolPolicy::Preserve>::Storage> std::make_shared<marl::BoundedPool<sw::DrawCall::BatchData,16,marl::PoolPolicy::Preserve>::Storage,>(void)' being compiled
...\VC\Tools\MSVC\14.16.27023\include\memory(1866): warning C4316: 'std::_Ref_count_obj<_Ty>': object allocated on the heap may not be aligned 16
        with
        [
            _Ty=marl::BoundedPool<sw::DrawCall::BatchData,16,marl::PoolPolicy::Preserve>::Storage
        ]

**Comment by c0d1f1ed** [comment]
Google bug: b/140575360
