### ISSUE TITLE
Add "marl/" prefix for public header-to-header includes

### ISSUE THREAD

**Issue by ben-clayton** [google/marl#54]
See https://github.com/google/marl/pull/53#discussion_r334900794 for more context.

**Comment by ben-clayton** [comment]
I've looked into this a bit, and I'm not sure if changing this gives any benefits.

The C++ spec states that the include search paths are implementation defined - so let's look at the compiler behaviours:

----

[gcc states](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html):
> "By default, the preprocessor looks for header files included by the quote form of the directive #include "file" first relative to the directory of the current file, and then in a preconfigured list of standard system directories"

(see also [this](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Directory-Options.html))

----

clang doesn't have any documentation that I could easily find, and [the search logic is complex](https://github.com/llvm-mirror/clang/blob/master/lib/Lex/PPDirectives.cpp#L718), however it looks to the untrained eye that it would search relative first.
(see also [this](https://discourse.mc-stan.org/t/clang-include-path-order/2787/3))

----

[msvc states](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?redirectedfrom=MSDN&view=vs-2019):

> The preprocessor searches for include files in this order:
> 1) In the same directory as the file that contains the #include statement.
> 2) In the directories of the currently opened include files, in the reverse order in which they were opened. The search begins in the directory of the parent include file and continues upward through the directories of any grandparent include files.
> 3) Along the path that's specified by each /I compiler option.
> 4) Along the paths that are specified by the INCLUDE environment variable.

----

So, it looks like quoted includes are de-facto searched relative to the directory containing the `#include` first.

I'm hesitant to change the public headers to include the `marl/` prefix, just in case someone wants to precompile the sources and customize the include paths in some weird way.

@digit-google - If you have evidence that suggests I've got this wrong, please feel free to correct me.

**Comment by digit-google** [comment]
Thanks looking into it and for pulling this documentation. I swear that when I started programming, some compilers handled this very differently (i.e. "current file" would refer to the current source file, not necessarily the header that contains the #include). But this was a really long time ago :-)

It looks like GCC, Clang and Visual Studio have converged to the same behaviour since, so this should be fine. Sorry for the noise then. I agree it's ok to leave the sources as they are.
