### ISSUE TITLE
Benchmark results available somewhere?

### ISSUE THREAD

**Issue by felixguendling** [google/marl#75]
Are the benchmark results available online? As a table or graph?
How does it compare to other implementations like Boost.fiber?

**Comment by ben-clayton** [comment]
I'm still actively collecting these, but these are what I have so far:

https://google.github.io/marl/benchmarks

A few changes to the scheduler landed in the past week, so I'll rerun these existing benchmarks. However, I do not expect vast differences.

I'm also looking into the performance difference of `Defer` and `BlockingCall` on Windows. It might be an issue with the benchmarks being too short - I'll know more in the next few days.

Once I've finished with the above, I'll put this link on the `README.md` front page.

> How does it compare to other implementations like Boost.fiber?

I haven't written benchmarks using other APIs yet, as I am less familiar with their APIs, and I don't want to give false impressions of like-for-like results if they're really not. Instead, I've written a couple of benchmarks using `std::thread`, `std::mutex` and `std::condition_variable`, that provide similar task executing algorithms, but without any of the marl scheduler / fiber smarts. You can see these as `SingleQueueTaskExecutor` and `MultiQueueTaskExecutor` at the bottom of the graphs page.

If you'd like build some benchmarks that you believe mirror a marl benchmark, I'm open to including this in the benchmarks page.

Thanks for your interest!
Ben

**Comment by felixguendling** [comment]
Thank you very much! Marl looks very promising. I especially like that it has built-in support for sanitizers.

Since (from my understanding) Boost.fiber tries to mimic the threading primitives from the standard library, I think a comparison like you did using `std::thread`, etc. could be possible with Boost.fiber too. I cannot promise I'll have time soon to add it to the benchmarks but I'll try.
