### ISSUE TITLE
Schedule tasks from within tasks

### ISSUE THREAD

**Issue by drywolf** [google/marl#89]
Hi, I've come to experiment with marl after having watched the GDC Talk "[Parallelizing the Naughty Dog Engine](https://www.gdcvault.com/play/1022186/Parallelizing-the-Naughty-Dog-Engine)".
I am wondering if it is intended by the marl API & scheduler that one can schedule tasks from within tasks.

In the talk (at 14:25) Christian Gyrling says that their engine / application heavily relies on this feature, to the point where their entire main-loop is just a graph of tasks which is kicked off by one task at the start of each frame.

Is there something to be aware of when doing this with marl ? Or maybe is it generally to be avoided ?
Thanks

**Comment by ben-clayton** [comment]
Hi @drywolf,

You can schedule tasks from anywhere (so long as a scheduler is bound), including from within other tasks.
I've created a new example that demonstrates this: https://github.com/google/marl/pull/90.

I hope this helps answer your question.

Cheers,
Ben

**Comment by drywolf** [comment]
Thanks a lot @ben-clayton for the clarification.

**Comment by ben-clayton** [comment]
You're very welcome.
